apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
    - name: http
      protocol: TCP
      port: 80 #service（对内）的端口
      targetPort: 80 #pod的端口
      nodePort: 30002 #service（对外）的端口
