apiVersion: v1
kind: Service
metadata:
  name: tmall
  namespace: tmall
  labels:
    app: tmall-adonis-service
spec:
  type: NodePort
  selector:
    app: tmall_adonis-service-pod
  ports:
    - name: http
      protocol: TCP
      port: 3000 #service（对内）的端口
      targetPort: 3000 #pod的端口
      nodePort: 30001 #service（对外）的端口
